name: "plome_postprocess"
backend: "python"
max_batch_size: 16
input [
  {
    name: "INPUT_SENTENCE"
    data_type: TYPE_INT64
    dims: [ 180 ]
  },
  {
    name: "CSC_MASKS"
    data_type: TYPE_INT64
    dims: [ 180 ]
  },
  {
    name: "CONFUSION_PREDS"
    data_type: TYPE_FP32
    dims: [ 180,21128 ]
  }
]
output [
  {
    name: "RAW_SENTENCE"
    data_type: TYPE_STRING 
    dims: [ -1 ]
  },
  {
    name: "CSC_SENTENCE"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

instance_group [{ kind: KIND_CPU }]
